eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:    
      routes:
      # конфигурация маршрута до микросервисов:
      # Веб-сервис склада магазина
        - id: store_warehouse
          uri: http://localhost:8082/
          predicates:
            - Path=/storage/index.html
      # Веб-сервис торгового зала
        - id: storefront
          uri: http://localhost:8083/
          predicates:
            - Path=/storefront/**
      # Веб-сервис банка
        - id: bank
          uri: http://localhost:8081/
          predicates:
            - Path=/bank/**
      # Сервер ресурсов магазина
        - id: store_resource_server
          uri: http://localhost:8084/
          predicates:
            - Path=/store_server/**
      # Сервис ресурсов банка
        - id: bank_resource_server
          uri: http://localhost:8085/
          predicates:
            - Path=/bank_server/**
