eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:    
      routes:
        - id: store_warehouse
          uri: http://localhost:8082/
          predicates:
            - Path=/storage/**
        - id: storefront
          uri: http://localhost:8083/
          predicates:
            - Path=/storefront/**